version: 2

seeds:
  - name: etablissement_enfants
    description: "Établissements d’accueil (multi-accueil, familial, etc.) avec informations de localisation, capacité et gestion"
    columns:
      - name: nom
        description: "Nom de l’établissement"
        tests:
          - not_null
      - name: type
        description: "Type d’établissement (Multi-accueil, Accueil familial, etc.)"
        tests:
          - not_null
      - name: code_postal
        description: "Code postal"
      - name: commune
        description: "Nom de la commune"
        tests:
          - not_null
      - name: code_insee
        description: "Code INSEE de la commune"
      - name: capacite
        description: "Capacité d’accueil"

  - name: agrements_assistants_matern_dep
    description: "Liste des assistantes maternelles aggrées par département (2010-2023)"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: code_departement
        description: "Code INSEE du département"
        tests:
          - not_null
      - name: departement
        description: "Nom du département"

  - name: agrements_assistants_matern_reg
    description: "Agréments d’assistants maternels par region (2010–2023)"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: libelle_region
        description: "Libellé de la région"

  - name: etablissements_creches_dep
    description: "Liste des crèches par département (2010-2023)"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: code_departement
        description: "Code INSEE du département"
        tests:
          - not_null
      - name: departement
        description: "Nom du département"
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023
      
  - name: etablissements_creches_reg
    description: "Liste des crèches par  region (2010–2023)"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: libelle_region
        description: "Libellé de la région"
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023

  - name: places_creches_collectives_dep
    description: "Liste des crèches places en crèches collectives par département (2010-2023)"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: code_departement
        description: "Code INSEE du département"
        tests:
          - not_null
      - name: departement
        description: "Nom du département"
      - name: Y2010
      - name: Y2011
      - name: Y2012
      - name: Y2013
      - name: Y2014
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023
      
  - name: places_eaje_all
    description: "Ensemble des places disponibles EAJE"
    columns:
      - name: code_region
        description: "Code INSEE de la région"
        tests:
          - not_null
      - name: libelle_region
        description: "Libellé de la région"
      - name: creches_collectives
      - name: creches_familiales
      - name: multi_accueil_collectif_familial
      - name: jardins_enfants
      - name: etab_et_services_gestion_parentale
      - name: total