version: 2

models:
  - name: stg__etablissement_enfants
    description: "Table de staging des établissements d’accueil d’enfants"
    columns:
      - name: nom
        description: "Nom de l’établissement"
        tests: [not_null]
      - name: type
        description: "Type d’établissement"
      - name: code_postal
        description: "Code postal"
      - name: commune
        description: "Nom de la commune"      
      - name: code_insee
        description: "Code INSEE de la commune"
      - name: capacite
        description: "Capacité d’accueil"
    
  - name: stg__agrements_assistants_mater_dep
    description: "Staging assistantes maternelles departement"
    columns:
      - name: code_region
      - name: code_departement
      - name: departement
      - name: Y2010
      - name: Y2011
      - name: Y2012
      - name: Y2013
      - name: Y2014
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023

  - name: stg__agrements_assistants_mater_reg
    description: "Staging assistantes maternelles region"
    columns:
      - name: code_region
      - name: code_region
      - name: libelle_region
      - name: Y2010
      - name: Y2011
      - name: Y2012
      - name: Y2013
      - name: Y2014
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023

  - name: stg__places_creches_collectives_dep
    description: "Places crèches collectives departement"
    columns:
      - name: code_region
      - name: code_departement
      - name: departement
      - name: Y2010
      - name: Y2011
      - name: Y2012
      - name: Y2013
      - name: Y2014
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023

  - name: places_eaje_all
    description: "Places crèches collectives region"
    columns:
      - name: code_region
      - name: code_region
      - name: libelle_region
      - name: Y2010
      - name: Y2011
      - name: Y2012
      - name: Y2013
      - name: Y2014
      - name: Y2015
      - name: Y2016
      - name: Y2017
      - name: Y2018
      - name: Y2019
      - name: Y2020
      - name: Y2021
      - name: Y2022
      - name: Y2023